
export const SINGLE_WORKER_ANSWER_REQUEST = 'SINGLE_WORKER_ANSWER_REQUEST'
export const SINGLE_WORKER_ANSWER_SUCCESS = 'SINGLE_WORKER_ANSWER_SUCCESS'
export const SINGLE_WORKER_ANSWER_FAILED = 'SINGLE_WORKER_ANSWER_FAILED'