export const QUESTION_REQUEST = 'QUESTION_REQUEST'
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS'
export const QUESTION_FAILED = 'QUESTION_FAILED'

export const QUESTION_ADD_REQUEST = 'QUESTION_ADD_REQUEST'
export const QUESTION_ADD_SUCCESS = 'QUESTION_ADD_SUCCESS'
export const QUESTION_ADD_FAILED = 'QUESTION_ADD_FAILED'

export const SINGLE_QUESTION_ADD_REQUEST = 'SINGLE_QUESTION_ADD_REQUEST'
export const SINGLE_QUESTION_ADD_SUCCESS = 'SINGLE_QUESTION_ADD_SUCCESS'
export const SINGLE_QUESTION_ADD_FAILED = 'SINGLE_QUESTION_ADD_FAILED'

export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST'
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_DELETE_FAILED = 'QUESTION_DELETE_FAILED'
