export const QUESTION_REQUEST = 'QUESTION_REQUEST'
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS'
export const QUESTION_FAILED = 'QUESTION_FAILED'

export const QUESTION_ADD_REQUEST = 'QUESTION_ADD_REQUEST'
export const QUESTION_ADD_SUCCESS = 'QUESTION_ADD_SUCCESS'
export const QUESTION_ADD_FAILED = 'QUESTION_ADD_FAILED'
